### ISSUE TITLE
issue in the vcpkg installation for qt5 libraries with triplet support

### ISSUE THREAD

**Issue by apattnaik0721013** [paul-michalik/vcpkg#2]
with vcpkg (0.0.81-5), it failed to install qt5 with triplet format.
i tried the following to install qt5:
vcpkg.exe install qt5:x86-windows-v140

**Comment by paul-michalik** [comment]
We need to upgrade the triplets by [Per-port customization](https://vcpkg.readthedocs.io/en/latest/users/triplets/). The example shows exactly our use case... ☺

**Comment by paul-michalik** [comment]
Closing since this has been merged and is considered finished.
